version: '3'

services:
  web:
    build: .  
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./main/:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test@1234
      - POSTGRES_DB=worker_db

    expose:
      - 5432

volumes:
  postgres_data: